import { TOKEN_TYPES, type TokenType } from "@syntax/token";

const KEYWORD = "text-[#F472B6] font-semibold"; 
const TYPE = "text-[#34D399]";                 
const STRING = "text-[#FCD34D]";                
const NUMBER = "text-[#A78BFA]";   
const COMMENT = "text-[#6B7280] italic";  
const ERROR = "error-token"           

const FUNCTION = "text-[#FBBF24]";              
const MODULE = "text-[#38BDF8]";                

const BUILTIN = "text-[#60A5FA]"; 
const PRINT = "text-[#F97316]"             
const OPERATOR = "text-[#94A3B8]";
const VARIABLE = "text-[#CBD5E1]";
const PARAMETER = "text-[#E2E8F0]";
const CONSTANT = "text-[#C084FC]";
const PUNCTUATION = "text-[#64748B]";

export const TOKEN_THEME: Record<TokenType, string> = {
  // Literals
  [TOKEN_TYPES.NUMBER]: NUMBER,
  [TOKEN_TYPES.STRING]: STRING,
  [TOKEN_TYPES.BOOLEAN]: KEYWORD,
  [TOKEN_TYPES.NULL]: KEYWORD,

  // Identifiers
  [TOKEN_TYPES.IDENTIFIER]: VARIABLE,

  // Keywords
  [TOKEN_TYPES.PRINT]: PRINT,
  [TOKEN_TYPES.IF]: KEYWORD,
  [TOKEN_TYPES.ELSE]: KEYWORD,

  [TOKEN_TYPES.WHILE]: KEYWORD,
  [TOKEN_TYPES.FOR]: KEYWORD,
  [TOKEN_TYPES.IN]: KEYWORD,

  [TOKEN_TYPES.BREAK]: KEYWORD,
  [TOKEN_TYPES.CONTINUE]: KEYWORD,

  [TOKEN_TYPES.FN]: BUILTIN,
  [TOKEN_TYPES.RETURN]: KEYWORD,

  [TOKEN_TYPES.IMPORT]: BUILTIN,
  [TOKEN_TYPES.FROM]: BUILTIN,
  [TOKEN_TYPES.EXPORT]: BUILTIN,
  [TOKEN_TYPES.AS]: BUILTIN,

  // Types
  [TOKEN_TYPES.TYPE]: TYPE,

  // Operators
  [TOKEN_TYPES.PLUS]: OPERATOR,
  [TOKEN_TYPES.MINUS]: OPERATOR,
  [TOKEN_TYPES.STAR]: OPERATOR,
  [TOKEN_TYPES.SLASH]: OPERATOR,
  [TOKEN_TYPES.MODULO]: OPERATOR,

  [TOKEN_TYPES.EQUAL_EQUAL]: OPERATOR,
  [TOKEN_TYPES.NOT_EQUAL]: OPERATOR,

  [TOKEN_TYPES.LESS]: OPERATOR,
  [TOKEN_TYPES.GREATER]: OPERATOR,

  [TOKEN_TYPES.LESS_EQUAL]: OPERATOR,
  [TOKEN_TYPES.GREATER_EQUAL]: OPERATOR,

  [TOKEN_TYPES.AND]: OPERATOR,
  [TOKEN_TYPES.OR]: OPERATOR,
  [TOKEN_TYPES.NOT]: OPERATOR,

  [TOKEN_TYPES.RANGE_EXCLUSIVE]: OPERATOR,
  [TOKEN_TYPES.RANGE_INCLUSIVE]: OPERATOR,

  // Symbols
  [TOKEN_TYPES.COLON]: PUNCTUATION,
  [TOKEN_TYPES.DOUBLE_COLON]: PUNCTUATION,
  [TOKEN_TYPES.EQUALS]: OPERATOR,

  [TOKEN_TYPES.LPAREN]: PUNCTUATION,
  [TOKEN_TYPES.RPAREN]: PUNCTUATION,

  [TOKEN_TYPES.LBRACKET]: PUNCTUATION,
  [TOKEN_TYPES.RBRACKET]: PUNCTUATION,

  [TOKEN_TYPES.LBRACE]: PUNCTUATION,
  [TOKEN_TYPES.RBRACE]: PUNCTUATION,

  [TOKEN_TYPES.DOT]: PUNCTUATION,
  [TOKEN_TYPES.QUESTION]: PUNCTUATION,
  [TOKEN_TYPES.COMMA]: PUNCTUATION,

  [TOKEN_TYPES.ARROW]: OPERATOR,

  // Special
  [TOKEN_TYPES.WHITESPACE]: "",
  [TOKEN_TYPES.COMMENT]: COMMENT,
  [TOKEN_TYPES.ERROR]: ERROR,
  [TOKEN_TYPES.NEWLINE]: "",
  [TOKEN_TYPES.EOF]: "",
};

export const SEMANTIC_THEME: Record<string, string> = {
  FUNCTION: FUNCTION,        
  VARIABLE: VARIABLE,
  PARAMETER: PARAMETER,
  CONSTANT: CONSTANT,
  SCHEMA: TYPE,
  MODULE: MODULE,           
  MODULE_MEMBER: FUNCTION,  
};
